"""add passport photo fields to user

Revision ID: 40f8eaf91263
Revises: be88f3380de6
Create Date: 2025-07-03 08:42:26.655168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f8eaf91263'
down_revision: Union[str, Sequence[str], None] = 'be88f3380de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite не поддерживает ALTER COLUMN, поэтому убираем эту операцию
    # op.alter_column('equipment', 'is_deleted',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    op.add_column('users', sa.Column('passport_photo_front', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_photo_back', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passport_photo_back')
    op.drop_column('users', 'passport_photo_front')
    # SQLite не поддерживает ALTER COLUMN, поэтому убираем эту операцию
    # op.alter_column('equipment', 'is_deleted',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # ### end Alembic commands ###
