"""Add stores table

Revision ID: 98a16557f250
Revises: 40f8eaf91263
Create Date: 2025-07-05 16:59:11.698284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a16557f250'
down_revision: Union[str, Sequence[str], None] = '40f8eaf91263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_email'), 'stores', ['email'], unique=True)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.drop_index(op.f('ix_rental_items_id'), table_name='rental_items')
    op.drop_table('rental_items')
    op.add_column('categories', sa.Column('store_id', sa.Integer(), nullable=False))
    op.alter_column('categories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'categories', 'stores', ['store_id'], ['id'])
    op.drop_column('categories', 'description')
    op.add_column('equipment', sa.Column('store_id', sa.Integer(), nullable=False))
    op.alter_column('equipment', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment', 'quantity_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment', 'quantity_available',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipment', 'price_per_day',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('equipment', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'equipment', 'stores', ['store_id'], ['id'])
    op.alter_column('equipment_movements', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.add_column('rentals', sa.Column('store_id', sa.Integer(), nullable=False))
    op.alter_column('rentals', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'rentals', 'stores', ['store_id'], ['id'])
    op.add_column('users', sa.Column('store_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('superadmin', 'store_admin', 'staff', 'viewer', 'client', name='userrole'),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('superadmin', 'store_admin', 'staff', 'viewer', 'client', name='userrole'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('users', 'store_id')
    op.drop_constraint(None, 'rentals', type_='foreignkey')
    op.alter_column('rentals', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('rentals', 'store_id')
    op.alter_column('equipment_movements', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.alter_column('equipment', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('equipment', 'price_per_day',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=False)
    op.alter_column('equipment', 'quantity_available',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipment', 'quantity_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('equipment', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('equipment', 'store_id')
    op.add_column('categories', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.alter_column('categories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('categories', 'store_id')
    op.create_table('rental_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rental_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price_per_day', sa.FLOAT(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_items_id'), 'rental_items', ['id'], unique=False)
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_email'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
