"""add unique email per store for users

Revision ID: c42714155ff5
Revises: 25d943e73aa1
Create Date: 2025-07-07 09:18:08.943966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42714155ff5'
down_revision: Union[str, Sequence[str], None] = '25d943e73aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email_store', 'users', ['email', 'store_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email_store', 'users', type_='unique')
    # ### end Alembic commands ###
